"""Exportação unificada dos modelos SQLAlchemy de todas as frentes (CPA, DATASUS, SIGTAP)."""

from scripts.shared.models.base import Base

from scripts.shared.models.cpa import (
    CpaImportacao,
    CpaImportacaoChangelog,
    Instituicao,
    Vinculo,
    Aditivo,
    PlanoOperativo,
    PlanoOperativoProcedimento,
    ComplementacaoTipo,
    ComplementacaoItem,
    PlanoOperativoComplementacao,
    tipo_vinculo_enum,
    tipo_instituicao_enum,
    tipo_aditivo_enum,
    tipo_operacao_enum,
    tipo_complexidade_enum,
)

from scripts.shared.models.datasus import (
    DatasusImportacao,
    DatasusSihTbRd,
    DatasusSihRd,
    DatasusSiaTbPa,
    DatasusSiaPa,
)

from scripts.shared.models.sigtap import (
    SigtapImportacao,
    SigtapChangelog,
    SigtapProcedimento,
    SigtapFinanciamento,
    SigtapRubrica,
    SigtapDetalhe,
    SigtapDescricaoDetalhe,
    SigtapRegistro,
    SigtapServico,
    SigtapServicoClassificacao,
    SigtapModalidade,
    SigtapTipoLeito,
    SigtapCid,
    SigtapOcupacao,
    SigtapHabilitacao,
    SigtapGrupo,
    SigtapSubGrupo,
    SigtapFormaOrganizacao,
    SigtapSiaSih,
    SigtapGrupoHabilitacao,
    SigtapDescricao,
    SigtapRegraCondicionada,
    SigtapRedeAtencao,
    SigtapComponenteRede,
    SigtapTuss,
    SigtapRenases,
)

__all__ = [
    "Base",
    # CPA
    "CpaImportacao",
    "CpaImportacaoChangelog",
    "Instituicao",
    "Vinculo",
    "Aditivo",
    "PlanoOperativo",
    "PlanoOperativoProcedimento",
    "ComplementacaoTipo",
    "ComplementacaoItem",
    "PlanoOperativoComplementacao",
    "tipo_vinculo_enum",
    "tipo_instituicao_enum",
    "tipo_aditivo_enum",
    "tipo_operacao_enum",
    "tipo_complexidade_enum",
    # DATASUS
    "DatasusImportacao",
    "DatasusSihTbRd",
    "DatasusSihRd",
    "DatasusSiaTbPa",
    "DatasusSiaPa",
    # SIGTAP
    "SigtapImportacao",
    "SigtapChangelog",
    "SigtapProcedimento",
    "SigtapFinanciamento",
    "SigtapRubrica",
    "SigtapDetalhe",
    "SigtapDescricaoDetalhe",
    "SigtapRegistro",
    "SigtapServico",
    "SigtapServicoClassificacao",
    "SigtapModalidade",
    "SigtapTipoLeito",
    "SigtapCid",
    "SigtapOcupacao",
    "SigtapHabilitacao",
    "SigtapGrupo",
    "SigtapSubGrupo",
    "SigtapFormaOrganizacao",
    "SigtapSiaSih",
    "SigtapGrupoHabilitacao",
    "SigtapDescricao",
    "SigtapRegraCondicionada",
    "SigtapRedeAtencao",
    "SigtapComponenteRede",
    "SigtapTuss",
    "SigtapRenases",
]
