# ==============================================================================
# Dockerfile para Frontend Angular 22 (Desenvolvimento Local / Hot-Reload)
# ==============================================================================
FROM node:22-alpine

WORKDIR /app

# Instala todas as dependências
COPY package*.json ./
RUN npm install

# Copia código e configurações base
COPY . .

EXPOSE 4200

CMD ["npx", "ng", "serve", "--host", "0.0.0.0", "--port", "4200", "--poll", "2000"]
