[project]
name = "sync-datasus"
version = "0.1.0"
description = ""
authors = [
    {name = "Pablo Santos",email = "pabloeduardossantos@gmail.com"}
]
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "pandas>=2.2.0,<3.0.0",
    "openpyxl>=3.1.0,<4.0.0",
    "sqlalchemy (>=2.0.51,<3.0.0)",
]

[tool.poetry]
packages = [{include = "sync_datasus", from = "src"}]

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
